In [1]:
import numpy as np
import torch

In [3]:
inputs = np.array([[73, 67, 43],[91, 88, 64],[87, 134, 58],[102, 43, 37],[69, 96,70]], dtype = 'float32')
print(inputs)

[[ 73.  67.  43.]
 [ 91.  88.  64.]
 [ 87. 134.  58.]
 [102.  43.  37.]
 [ 69.  96.  70.]]


In [4]:
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype = 'float32')
print(targets)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [5]:
#convert from numpy to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


### Linear Regression Model

In [9]:
#Weights and Biases
w = torch.randn(2, 3, requires_grad = True)
b = torch.randn(2, requires_grad = True)
print(w)
print(b)
#randn = rand + n (n denotes normal distribution)

tensor([[ 1.0288,  0.0581, -0.7555],
        [-1.0819,  1.8592, -1.1363]], requires_grad=True)
tensor([-0.1646, -0.4856], requires_grad=True)


In [10]:
def model(x):
    return x @ w.t() + b
#@ -> matmul, w.t -> transpose

In [11]:
preds = model(inputs)
print(preds)

tensor([[ 46.3408,  -3.7578],
        [ 50.2129,  -8.0508],
        [ 53.3037,  88.6191],
        [ 79.3132, -72.9366],
        [ 23.5120,  23.8070]], grad_fn=<AddBackward0>)


In [12]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [13]:
def mse(t1,t2):
    diff = t1 - t2
    return torch.sum(diff*diff)/diff.numel()

In [14]:
loss = mse(preds, targets)
print(loss)

tensor(5541.0029, grad_fn=<DivBackward0>)


In [15]:
loss.backward()

In [16]:
print(w)
print(w.grad)

tensor([[ 1.0288,  0.0581, -0.7555],
        [-1.0819,  1.8592, -1.1363]], requires_grad=True)
tensor([[-1772.2100, -3465.2231, -1927.9354],
        [-7390.1875, -6870.2173, -4691.2192]])


In [19]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [20]:
preds = model(inputs)
print(preds)

tensor([[ 59.6746,  32.2893],
        [ 67.9014,  39.2706],
        [ 75.2145, 143.6902],
        [ 91.3469, -36.2511],
        [ 41.2095,  68.7443]], grad_fn=<AddBackward0>)


In [21]:
loss = mse(preds, targets)
print(loss)

tensor(2396.7563, grad_fn=<DivBackward0>)


In [22]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ -384.6465, -1944.7421,  -995.8730],
        [-3675.8936, -2900.1326, -2236.0803]])
tensor([ -9.1306, -42.4514])


In [36]:
for i in range(100000):
    preds  = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad*1e-5
        b -= b.grad*1e-5
        w.grad.zero_()
        b.grad.zero_()

In [37]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(0.5041, grad_fn=<DivBackward0>)


In [38]:
print(preds)

tensor([[ 57.1347,  70.2278],
        [ 82.2259, 100.7211],
        [118.6981, 132.9718],
        [ 21.0852,  37.0254],
        [101.9156, 119.1249]], grad_fn=<AddBackward0>)


In [39]:
#That was cool!

In [40]:
import torch.nn as nn

In [41]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [42]:
from torch.utils.data import TensorDataset

In [43]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [44]:
from torch.utils.data import DataLoader

In [45]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle = True)

In [46]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[91., 88., 64.],
        [91., 87., 65.],
        [68., 96., 71.],
        [92., 87., 64.],
        [68., 97., 70.]])
tensor([[ 81., 101.],
        [ 80., 102.],
        [104., 118.],
        [ 82., 100.],
        [102., 120.]])


In [48]:
#Pytorch model
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.4496,  0.3685, -0.5512],
        [-0.2846, -0.4308,  0.2423]], requires_grad=True)
Parameter containing:
tensor([ 0.3954, -0.5631], requires_grad=True)


In [49]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.4496,  0.3685, -0.5512],
         [-0.2846, -0.4308,  0.2423]], requires_grad=True),
 Parameter containing:
 tensor([ 0.3954, -0.5631], requires_grad=True)]

In [50]:
preds = model(inputs)
preds

tensor([[ 34.1991, -39.7854],
        [ 38.4535, -48.8671],
        [ 56.9132, -69.0008],
        [ 41.7000, -39.1530],
        [ 28.2037, -44.5985],
        [ 34.2802, -39.6392],
        [ 37.5338, -48.1940],
        [ 56.8116, -69.0431],
        [ 41.6190, -39.2992],
        [ 27.2029, -44.0716],
        [ 33.2794, -39.1123],
        [ 38.5346, -48.7209],
        [ 57.8330, -69.6739],
        [ 42.7008, -39.6799],
        [ 28.1226, -44.7447]], grad_fn=<AddmmBackward0>)

In [51]:
import torch.nn.functional as F

In [52]:
loss_fn = F.mse_loss

In [53]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(11997.3750, grad_fn=<MseLossBackward0>)


In [54]:
#Define optimizer
opt = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [57]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    for epoch in range(num_epochs):
        for xb, yb in train_dl:
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
        if (epoch + 1) % 10 == 0:
            print('Epoch [{}/{}], Loss : {:.4f}'.format(epoch + 1, num_epochs, loss.item()))

In [58]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss : 1068.8104
Epoch [20/100], Loss : 267.3980
Epoch [30/100], Loss : 231.0134
Epoch [40/100], Loss : 130.6601
Epoch [50/100], Loss : 57.0788
Epoch [60/100], Loss : 59.5198
Epoch [70/100], Loss : 88.8360
Epoch [80/100], Loss : 63.6738
Epoch [90/100], Loss : 47.3811
Epoch [100/100], Loss : 27.5741


In [59]:
#Generate Predicitions
preds = model(inputs)
preds

tensor([[ 58.8129,  71.2625],
        [ 77.0649, 100.4830],
        [126.3420, 131.1006],
        [ 30.7550,  43.6114],
        [ 87.5087, 114.9070],
        [ 57.6472,  70.3411],
        [ 75.9319, 100.5126],
        [126.1442, 131.7150],
        [ 31.9207,  44.5328],
        [ 87.5415, 115.8580],
        [ 57.6799,  71.2921],
        [ 75.8992,  99.5616],
        [127.4750, 131.0710],
        [ 30.7223,  42.6603],
        [ 88.6744, 115.8284]], grad_fn=<AddmmBackward0>)