In [2]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import math
import string

In [5]:
w = torch.tensor(4., requires_grad = True)
b = torch.tensor(5., requires_grad = True)
x = torch.tensor(3.)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [6]:
y = w*x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [7]:
y.backward()

In [12]:
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

#x.grad is none because x did not have requires_grad = true

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


## Tensor Linear Algebra

In [14]:
#vector x vector
tensor1 = torch.randn(3)
tensor2 = torch.randn(3)
tensor_mul = torch.matmul(tensor1, tensor2)
print(tensor1, tensor2, tensor_mul)

tensor([-0.8848, -1.1190,  0.1527]) tensor([-0.7920, -1.2854,  1.0164]) tensor(2.2943)


In [16]:
#matrix x vector
tensor1 = torch.randn(3, 4)
tensor2 = torch.randn(4)
tensor_mul = torch.matmul(tensor1, tensor2)
print(tensor1, tensor2, tensor_mul)

tensor([[-0.5227,  0.7067,  3.0799, -0.2249],
        [-1.5688, -0.6236, -0.0922,  0.6225],
        [ 0.5522,  0.2804, -0.8742, -0.3212]]) tensor([-0.7384, -0.8211, -0.7573, -0.4947]) tensor([-2.4155,  1.4323,  0.1829])


In [17]:
#batched_matrix x broadcasted_vector
tensor1 = torch.randn(5, 3, 4)
tensor2 = torch.randn(4)
tensor_mul = torch.matmul(tensor1, tensor2)
print(tensor1, tensor2, tensor_mul)

tensor([[[-0.7221, -0.6418,  0.3528, -1.2022],
         [ 0.2008, -0.5134,  0.0768,  1.2635],
         [-0.0690,  1.9951,  0.0078,  0.5546]],

        [[-1.1451, -0.7529,  0.4835,  0.4306],
         [ 0.3522,  1.5214,  1.4959, -0.4116],
         [-0.9038,  0.2588,  1.1083, -0.0614]],

        [[ 0.3209,  0.8080, -0.4592, -0.6854],
         [ 1.0170,  0.5262,  0.2775,  1.7900],
         [ 0.6783, -1.3076, -0.8065, -0.1680]],

        [[-0.6356,  0.0795,  0.4671, -0.3999],
         [ 0.3696, -1.6779, -0.6771, -1.0361],
         [ 0.0644, -0.2453,  1.2481, -2.0042]],

        [[-0.6787,  0.5219,  1.2341,  0.1921],
         [-0.0883, -1.2737, -0.1289,  0.4697],
         [ 1.2984, -1.4054,  0.4335, -1.3861]]]) tensor([-1.2493e+00,  6.2658e-04, -6.5833e-01,  6.5180e-01]) tensor([[-0.1141,  0.5218,  0.4437],
        [ 1.3924, -1.6921,  0.3596],
        [-0.5448, -0.2862, -0.4268],
        [ 0.2260, -0.6924, -2.2087],
        [ 0.1610,  0.5005, -2.8118]])


In [24]:
#batched_matrix x batched_matrix
tensor1 = torch.randn(2, 3, 4)
tensor2 = torch.randn(2, 4, 6)
tensor_mul = torch.matmul(tensor1, tensor2)
print(tensor1)
print(tensor2)
print(tensor_mul)

tensor([[[-0.3565, -0.1961,  0.4234, -0.0410],
         [ 0.0065,  0.1008,  0.4682,  0.3535],
         [-1.1407,  0.2230, -1.8468,  1.3114]],

        [[ 0.7479,  0.0041, -1.2331,  1.4438],
         [-1.2660,  1.8907, -0.8328, -1.0041],
         [-1.9924, -1.0461,  0.2423, -0.4344]]])
tensor([[[ 1.2301,  0.8628,  1.0071,  1.3859, -0.2916, -0.1723],
         [ 0.1275,  0.1511,  0.1656, -0.0475,  0.1431, -1.3835],
         [ 0.1099, -0.3227,  0.1750,  0.3990,  0.1452,  1.5474],
         [-0.7406, -0.6928,  0.8455, -0.4754,  0.2976, -0.4118]],

        [[-2.0113,  0.4166, -1.1291,  1.9896, -0.8894,  1.0246],
         [-0.8220, -0.7206, -1.6356, -0.8284,  0.3835, -0.9911],
         [-1.0823,  0.6986,  0.5274,  1.1678,  2.8210, -0.8731],
         [ 1.5473, -1.7304, -1.6937, -1.4918,  0.4025,  0.9816]]])
tensor([[[-0.3866, -0.4454, -0.3520, -0.2962,  0.1252,  1.0048],
         [-0.1894, -0.3751,  0.4041,  0.0230,  0.1857,  0.4384],
         [-2.5491, -1.2631, -0.3263, -2.9519,  0.4868, -3.50

In [25]:
#Matrix Exponentiation
A = torch.randn(3,3)
Pow_A = torch.linalg.matrix_power(A,0)
print(Pow_A)
Pow_A = torch.linalg.matrix_power(A,1)
print(Pow_A)
Pow_A = torch.linalg.matrix_power(A,-1)
print(Pow_A)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[ 0.5300,  1.1512, -2.3656],
        [-1.3649,  0.6012,  1.4101],
        [-0.1379,  0.6712,  1.1088]])
tensor([[-0.0837, -0.8572,  0.9115],
        [ 0.3948,  0.0783,  0.7427],
        [-0.2494, -0.1540,  0.5656]])


In [27]:
#Dot product
A = torch.randn(4,3)
B = torch.ones(4,3)
C = torch.linalg.vecdot(A,B)
print(A)
print(B)
print(C)

tensor([[-0.6930,  2.7602,  0.4615],
        [-0.7028, -0.2396,  0.6510],
        [ 1.1072,  0.8006, -0.5818],
        [ 0.2106, -0.8486,  0.5150]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([ 2.5287, -0.2914,  1.3260, -0.1230])
